user www-data;
worker_processes auto;

pid /run/nginx.pid;

events {
	worker_connections 1024;
}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	sendfile on;
	keepalive_timeout 65;

	access_log /dev/stdout;
	error_log /dev/stderr;

	server {
		listen 443 ssl;
		server_name vfidelis.42.fr;

		ssl_protocols TLSv1.2 TLSv1.3;

		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		root /var/www/html;
		index index.php index.html;

		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		location ~ \.php$ {
			try_files $uri =404;

			include fastcgi_params;

			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;

			fastcgi_param SCRIPT_FILENAME \
				$document_root$fastcgi_script_name;
		}
	}
}