services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:inception
    container_name: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:inception
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - db_password
      - wp_password
      - wp_root_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

  nginx:
    build: ./requirements/nginx
    image: nginx:inception
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_password:
    file: ./secrets/wp_password.txt
  wp_root_password:
    file: ./secrets/wp_root_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vfidelis/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vfidelis/data/wordpress

networks:
  inception:
    driver: bridge
